server:
  port: 8888
  servlet:
    context-path: /sso
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  # 环境 dev|test|prod
#  profiles:
#    active: dev
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.yuguang.datasourceswitch.pojo
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_EMPTY
      #驼峰下划线转换
      #      db-column-underline: true
      table-underline: true
      #刷新mapper 调试神器
      #      refresh-mapper: true
      #数据库大写下划线转换
      #capital-mode: true
      #序列接口实现类配置
      #key-generator: com.baomidou.springboot.xxx
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
    banner: false
cas:
  cas-server-login-url: http://131.107.26.10:8080/cas/login
  cas-server-url-prefix: http://131.107.26.10:8080/cas
  skipUrls: /api/index,/api/login
  loginUserHandle: com.bonc.security.sso.SSOAuthHandle
#  线上测试
#  server-name: http://131.107.26.11:8888
#  本地测试
  server-name: http://192.168.110.195:8888
  encoding: UTF-8
  characterEncoding: UTF-8
  singleSignOut: true
sso:
  loginName: admin
  passWord: XVRIcRFykexhQzEqMJKXVqLIDrM%3D
  webUrl: http://131.107.26.10:8080/cas/login?service=http%3A%2F%2F131.107.26.10%3A8080%2Fportal%2FpageView%3FpageId%3Dindex
